[build]
  command = "export NODE_ENV=development && npm install && export NODE_ENV=production && npm run build"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_VERSION = "20"

# Production context
[context.production]
  environment = { NODE_ENV = "production" }

# Development context (deploys from git branches)
[context.branch-deploy]
  environment = { NODE_ENV = "development" }

# Preview context (deploy previews from pull/merge requests)
[context.deploy-preview]
  environment = { NODE_ENV = "development" }

# Environment variables
[template.environment]
  DATABASE_URL = "Required: NeonDB owner role connection string"
  DATABASE_AUTHENTICATED_URL = "Required: NeonDB authenticated role connection string"
  NEXT_PUBLIC_AZURE_AD_B2C_CLIENT_ID = "Required: Azure AD B2C client ID"